### ISSUE TITLE
Why initialize l_i as 1

### ISSUE THREAD

**Issue by feifeibear** [INT-FlashAttention2024/INT-FlashAttention#2]
https://github.com/thu-ml/SageAttention/pull/30

I noticed that your repo is very similar to the SageAttention. I guess it may be copied from the code here.
And why both of you initialize l_i as 1s. As far as I known, it should be initialized as torch.zeros.

**Comment by Ezio-csm** [comment]
> https://github.com/thu-ml/SageAttention/pull/30
> 
> 
> 
> I noticed that your repo is very similar to the SageAttention. I guess it may be copied from the code here.
> 
> And why both of you initialize l_i as 1s. As far as I known, it should be initialized as torch.zeros.

Yes you're right. But coincidentally m_i initialized as -inf and we got l_i = l_i * exp2(m_i - m_ij) + l_ij at the begin, actually the value of l_i have no influence to the result.

**Comment by feifeibear** [comment]
> > [thu-ml/SageAttention#30](https://github.com/thu-ml/SageAttention/pull/30)
> > I noticed that your repo is very similar to the SageAttention. I guess it may be copied from the code here.
> > And why both of you initialize l_i as 1s. As far as I known, it should be initialized as torch.zeros.
> 
> Yes you're right. But coincidentally m_i initialized as -inf and we got l_i = l_i * exp2(m_i - m_ij) + l_ij at the begin, actually the value of l_i have no influence to the result.

I understand, the official flash attention triton version implemented in this way.
